export const defaultStoreOrderFields = [
  'id',
  'status',
  'display_id',
  'version',
  'items.*',
  // 'items.order_line_item_extension.*',
  'currency_code',
  'total',
  'created_at',
  'updated_at',
  'customer_id',
  'sales_channel_id',
  'order_set.id',
  'order_set.ui_order_set_id',
  'order_set.cart_id',
  'order_set.customer_id',
  'order_set.payment_collection_id',
  'order_set.payment_collection.*',
  'order_set.payment_collection.payments.*',
  'order_set.status',
  'fulfillments.*',
  'payment_collections.*',
  'items.order_line_item_extension.status',
  'items.order_line_item_extension.id',
  'items.order_line_item_extension.reason',
  'items.order_line_item_extension.reason_code',
  'items.order_line_item_extension.returnable_flag',
  'items.order_line_item_extension.return_no_of_days',
  'items.order_line_item_extension.return_end_date',
  'items.order_line_item_extension.created_at',
  'items.order_line_item_extension.accepted_at',
  'items.order_line_item_extension.rejected_at',
  'items.order_line_item_extension.cancelled_at',
  'items.order_line_item_extension.packed_at',
  'items.order_line_item_extension.shipped_at',
  'items.order_line_item_extension.delivered_at',
  'items.order_line_item_extension.item_total',
  'items.order_line_item_extension.item_discount_total',
  'items.variant.*',
  'items.variant.metadata.*',
  'items.variant.options.*',
  'items.variant.product.*',
  'items.variant.product.options.*',
  'items.variant.product.categories.*',
  'items.variant.product.brand.*',
  'shipping_address.*',
  'payment_collections.payments.*',
]

// *items,+items.metadata,*items.variant,*items.product,*seller,*reviews,*order_set
export const defaultGetOrderFields = [
  'id',
  'status',
  // 'summary',
  'display_id',
  'total',
  'currency_code',
  // 'metadata',
  'created_at',
  'updated_at',

  // 'order_set.*',
  'order_set.order_delivery_detail',
  'order_set.status',
  // 'items',
  // 'items.metadata',
  'order_set.*',
  'items.variant.*',
  'items.product.*',
  // 'seller.*',
  'reviews.*',
  'payment_status',

  'item_total',
  'item_subtotal',
  'item_tax_total',
  'original_item_total',
  'original_item_subtotal',
  'original_item_tax_total',
  'shipping_total',
  'shipping_subtotal',
  'shipping_tax_total',
  'original_shipping_tax_total',
  'original_shipping_subtotal',
  'original_shipping_total',
  'items.id',
  'items.title',
  'items.quantity',
  'items.unit_price',
  'items.compare_at_unit_price',
  // 'items.raw_unit_price',
  // 'items.raw_compare_at_unit_price',
  'items.subtotal',
  'items.total',
  'items.discount_total',
  'items.discount_subtotal',
  'items.tax_total',
  'items.is_custom_price',
  'items.tax_lines.id',
  'items.tax_lines.rate',
  'items.adjustments.id',
  'items.adjustments.amount',
  'items.variant.id',
  'items.variant.title',
  'items.variant.sku',
  'items.variant.product.id',
  'items.variant.product.title',
  'items.variant.product.handle',
  // 'items.variant.metadsata',
  'items.detail.id',
  // 'items.order_line_item_extension.id',
  'items.order_line_item_extension.status',
  // 'items.order_line_item_extension.accepted_at',
  // 'items.order_line_item_extension.rejected_at',
  // 'items.order_line_item_extension.cancelled_at',
  // 'items.order_line_item_extension.packed_at',
  // 'items.order_line_item_extension.shipped_at',
  // 'items.order_line_item_extension.delivered_at',
  // 'items.order_line_item_extension.shipment_id',
  // 'items.order_line_item_extension.reason',
  // 'items.order_line_item_extension.reason_code',
  'items.order_line_item_extension.item_total',

  'seller.name',
  'seller.id',

    //"accounting_total": 8600,
  'summary.credit_line_total',
  'summary.transaction_total',
  'summary.pending_difference',
  'summary.paid_total',
  'summary.accounting_total',
  'summary.current_order_total',
  'summary.original_order_total',

  // 'items.metadata',
  // 'shipping_address.id',
  // 'shipping_address.first_name',
  // 'shipping_address.last_name',
  // 'shipping_address.address_1',
  // 'shipping_address.address_2',
  // 'shipping_address.city',
  // 'shipping_address.postal_code',
  // 'shipping_address.country_code',
  // 'shipping_address.province',
  // 'shipping_address.phone',

  // 'shipping_address.*',
  // 'billing_address.id',
  // 'billing_address.first_name',
  // 'billing_address.last_name',
  // 'billing_address.address_1',
  // 'billing_address.address_2',
  // 'billing_address.city',
  // 'billing_address.postal_code',
  // 'billing_address.country_code',
  // 'billing_address.province',
  // 'billing_address.phone',
  // 'shipping_methods.id',
  // 'shipping_methods.name',
  // 'shipping_methods.amount',
  // 'shipping_methods.tax_lines.id',
  // 'shipping_methods.tax_lines.rate',
  // 'shipping_methods.adjustments.id',
  // 'shipping_methods.adjustments.amount',
  // 'fulfillments.id',
  // 'fulfillments.location_id',
  // 'fulfillments.packed_at',
  // 'fulfillments.shipped_at',
  // 'fulfillments.delivered_at',
  // 'fulfillments.canceled_at',
  // 'fulfillments.items.id',
  // 'fulfillments.items.quantity',
  // 'fulfillments.labels.id',
  // 'fulfillments.labels.tracking_number',
  // 'customer.id',
  // 'customer.email',
  // 'customer.first_name',
  // 'customer.last_name',
  // 'order_set.id',
  // 'order_set.display_id',
  // Payment information
  // 'payment_collections.id',
  // 'payment_collections.status',
  // 'payment_collections.currency_code',
  // 'payment_collections.amount',
  // 'payment_collections.authorized_amount',
  // 'payment_collections.captured_amount',
  // 'payment_collections.refunded_amount',
  // 'payment_collections.payments.id',
  // 'payment_collections.payments.provider_id',
  // 'payment_collections.payments.amount',
  // 'payment_collections.payment_sessions.id',
  // 'payment_collections.payment_sessions.provider_id',
  // 'payment_collections.payment_sessions.status',
]

export const storeOrderQueryConfig = {
  list: {
    defaults: defaultStoreOrderFields,
    isList: true
  },
  retrieve: {
    defaults: defaultStoreOrderFields,
    isList: false
  }
}
