export const defaultAdminStockLocationFields = [
  "id",
  "name",
  "metadata",
  "created_at",
  "updated_at",
  "address.id",
  "address.address_1",
  "address.address_2",
  "address.city",
  "address.country_code",
  "address.phone",
  "address.province",
  "address.postal_code",
  "address.metadata",
  'stock_location_extension.id',
  'stock_location_extension.location_type',
  'stock_location_extension.address_type',
  'stock_location_extension.latitude',
  'stock_location_extension.longitude',
  'stock_location_extension.partner_id',
  'stock_location_extension.return_location_id',
  'stock_location_extension.status',
  'stock_location_extension.servisibility_status',
  'stock_location_extension.start_time',
  'stock_location_extension.end_time',
  'stock_location_extension.is_delay',
  'stock_location_extension.delay_value',
  'stock_location_extension.delay_message',
  'stock_location_section.id',
  'stock_location_section.address_type',
  'stock_location_section.partner_wh_code',
  'stock_location_section.lead_time',
  'stock_location_section.managed_by',
  'stock_location_section.stock_location_documents.id',
  'stock_location_section.stock_location_documents.stock_location_section_id',
  'stock_location_section.stock_location_documents.document_type',
  'stock_location_section.stock_location_documents.document_number',
  'stock_location_section.stock_location_documents.pdf_url',
  'stock_location_section.stock_location_contact.id',
  'stock_location_section.stock_location_contact.stock_location_section_id',
  'stock_location_section.stock_location_contact.first_name',
  'stock_location_section.stock_location_contact.last_name',
  'stock_location_section.stock_location_contact.email',
  'stock_location_section.stock_location_contact.phone_number',
  'stock_location_section.stock_location_id',
  'seller.*',
]

export const retrieveTransformQueryConfig = {
  defaults: defaultAdminStockLocationFields,
  isList: false,
}

export const listTransformQueryConfig = {
  ...retrieveTransformQueryConfig,
  isList: true,
}
