import { model } from "@medusajs/framework/utils"

export const PayoutTransactions = model.define("payout_transactions", {
  id: model.id().primaryKey(),
  provider: model.text(),
  provider_payout_id: model.text().index(),
  provider_fund_account_id: model.text().nullable(),
  return_id: model.text().index(),
  order_id: model.text().index(),
  payment_id: model.text().nullable(),
  customer_refund_method_id: model.text().nullable(),
  type: model.text().nullable(),
  type_id: model.text().nullable(),
  reference_id: model.text().nullable(),
  customer_id: model.text().index(),
  customer_name: model.text().nullable(),
  payout_type: model.text().nullable(),
  queue_if_low_balance: model.boolean().nullable(),
  idempotency_key: model.text(),
  amount: model.bigNumber(),
  currency: model.text().nullable(),
  payout_mode: model.text(),
  purpose: model.text().nullable(),
  notes: model.json().nullable(),
  utr: model.text().nullable(),
  status: model.text().nullable(),
  status_details: model.json().nullable(),
  fees: model.bigNumber().nullable(),
  tax: model.bigNumber().nullable(),
  last_webhook_event: model.text().nullable(),
  last_webhook_at: model.dateTime().nullable(),
  response_snapshot: model.json().nullable(),
  metadata: model.json().nullable(),
  created_by: model.text().nullable(),
})
