export const defaultPayoutTransactionsFields = [
  "id",
  "provider",
  "provider_payout_id",
  "provider_fund_account_id",
  "return_id",
  "order_id",
  "customer_refund_method_id",
  "reference_id",
  "customer_id",
  "customer_name",
  "payout_type",
  "queue_if_low_balance",
  "idempotency_key",
  "amount",
  "currency",
  "payout_mode",
  "purpose",
  "notes",
  "utr",
  "status",
  "status_details",
  "fees",
  "tax",
  "last_webhook_event",
  "last_webhook_at",
  "response_snapshot",
  "metadata",
  "created_by",
  "created_at",
  "updated_at",
  "type",
  "type_id",
]

export const payoutTransactionsQueryConfig = {
  list: {
    defaults: defaultPayoutTransactionsFields,
    isList: true,
  },
}
