export enum CartErrorStatusName {
  UNAUTHORIZED_USER = 'UNAUTHORIZED_USER',
  FORBIDDEN_USER = 'FORBIDDEN_USER',
  CART_REFRESH_FAILED = 'CART_REFRESH_FAILED',
  CART_NOT_LINKED_TO_CUSTOMER = 'CART_NOT_LINKED_TO_CUSTOMER',
  DELIVERY_DETAILS_MISSING = 'DELIVERY_DETAILS_MISSING',
  SHIPPING_ADDRESS_MISSING = 'SHIPPING_ADDRESS_MISSING',
  SHIPPING_ADDRESS_INCOMPLETE = 'SHIPPING_ADDRESS_INCOMPLETE',
  PAYMENT_COLLECTION_AMOUNT_MISMATCH = 'PAYMENT_COLLECTION_AMOUNT_MISMATCH',
  PAYMENT_AMOUNT_MISMATCH = 'PAYMENT_AMOUNT_MISMATCH',
  SOMETHING_WENT_WRONG = 'SOMETHING_WENT_WRONG',

  INSUFFICIENT_INVENTORY = 'INSUFFICIENT_INVENTORY',
}
