export enum MoEngageAlertName {
    LOGIN_OTP_WITH_HASH_CODE = 'login_otp_with_hash_code',
    ACCOUNT_CREATED = 'account_created',
    ORDER_PLACED = 'order_placed',
    PASSWORD_RESET = 'password_reset',
    ORDER_DELIVERY_OTP = 'order_delivery_otp',
    ORDER_DELIVERED_SUCCESSFULLY = 'delivered_successfully',
    ORDER_DELIVERY_FAILED = 'order_delivery_failed',
    ORDER_OUT_FOR_DELIVERY = 'out_for_delivery',
    ORDER_REAL_TIME_TRACKING = 'order_real_time_tracking',
    ORDER_REFUND_DONE = 'order_refund_done',
    ORDER_REFUND_INITIATED = 'refund_initiated',
    ORDER_REFUND_INITIATED_EMAIL = 'refund_inititated_email',
    ORDER_RETURN_CREATED = 'order_return_created',
    ORDER_RETURN_APPROVED = 'return_approved_270226',
    ORDER_RETURN_APPROVED_EMAIL = 'return_approved_email',
    ORDER_RETURN_CANCELLED = 'return_cancelled',
    ORDER_SET_CANCELLED = 'order_cancelled_2612',
    ITEM_CANCELLED = 'partial_cancellation',
    PAYMENT_FAILED = 'payment_failed',
  }