export const sellerOrderFields = [
  'id',
  'display_id',
  'status',
  'email',
  'currency_code',
  'version',
  'summary',
  'metadata',
  'created_at',
  'updated_at',
  'region_id',
  'total',
  'subtotal',
  'tax_total',
  'order_change',
  'discount_total',
  'discount_tax_total',
  'original_total',
  'original_tax_total',
  'item_total',
  'item_subtotal',
  'item_tax_total',
  'original_item_total',
  'original_item_subtotal',
  'original_item_tax_total',
  'shipping_total',
  'shipping_subtotal',
  'shipping_tax_total',
  'original_shipping_tax_total',
  'original_shipping_subtotal',
  'original_shipping_total',
  '*items',
  '*items.tax_lines',
  '*items.adjustments',
  '*items.variant',
  '*items.variant.product',
  '*items.detail',
  '*items.order_line_item_extension',
  '*shipping_address',
  '*billing_address',
  '*shipping_methods',
  '*shipping_methods.tax_lines',
  '*shipping_methods.adjustments',
  '*fulfillments',
  '*fulfillments.items',
  '*fulfillments.labels',
  '*customer',
  // 'order_set.order_delivery_detail',
]

// Fields for workflow - using internal MikroORM format
export const sellerOrderDefaultFields = [
  'id',
  'display_id',
  'status',
  'email',
  'currency_code',
  'version',
  'summary',
  'metadata',
  'created_at',
  'updated_at',
  'region_id',
  'total',
  'subtotal',
  'tax_total',
  'order_change',
  'discount_total',
  'discount_tax_total',
  'original_total',
  'original_tax_total',
  'item_total',
  'item_subtotal',
  'item_tax_total',
  'original_item_total',
  'original_item_subtotal',
  'original_item_tax_total',
  'shipping_total',
  'shipping_subtotal',
  'shipping_tax_total',
  'original_shipping_tax_total',
  'original_shipping_subtotal',
  'original_shipping_total',
  'items.id',
  'items.title',
  'items.quantity',
  'items.unit_price',
  'items.compare_at_unit_price',
  // 'items.raw_unit_price',
  // 'items.raw_compare_at_unit_price',
  'items.subtotal',
  'items.total',
  'items.discount_total',
  'items.discount_subtotal',
  'items.tax_total',
  'items.is_custom_price',
  'items.tax_lines.id',
  'items.tax_lines.rate',
  'items.adjustments.id',
  'items.adjustments.amount',
  'items.variant.id',
  'items.variant.title',
  'items.variant.sku',
  'items.variant.product.id',
  'items.variant.product.title',
  'items.variant.product.handle',
  'items.variant.metadata',
  'items.detail.id',
  'items.metadata',
  'items.order_line_item_extension.id',
  'items.order_line_item_extension.status',
  // 'items.order_line_item_extension.accepted_at',
  // 'items.order_line_item_extension.rejected_at',
  // 'items.order_line_item_extension.cancelled_at',
  // 'items.order_line_item_extension.packed_at',
  // 'items.order_line_item_extension.shipped_at',
  // 'items.order_line_item_extension.delivered_at',
  // 'items.order_line_item_extension.shipment_id',
  // 'items.order_line_item_extension.reason',
  // 'items.order_line_item_extension.reason_code',
  'shipping_address.id',
  'shipping_address.first_name',
  'shipping_address.last_name',
  'shipping_address.address_1',
  'shipping_address.address_2',
  'shipping_address.city',
  'shipping_address.postal_code',
  'shipping_address.country_code',
  'shipping_address.province',
  'shipping_address.phone',
  'shipping_address.metadata',

  // 'shipping_address.*',
  // 'billing_address.id',
  // 'billing_address.first_name',
  // 'billing_address.last_name',
  // 'billing_address.address_1',
  // 'billing_address.address_2',
  // 'billing_address.city',
  // 'billing_address.postal_code',
  // 'billing_address.country_code',
  // 'billing_address.province',
  // 'billing_address.phone',
  // 'shipping_methods.id',
  // 'shipping_methods.name',
  // 'shipping_methods.amount',
  // 'shipping_methods.tax_lines.id',
  // 'shipping_methods.tax_lines.rate',
  // 'shipping_methods.adjustments.id',
  // 'shipping_methods.adjustments.amount',
  // 'fulfillments.id',
  // 'fulfillments.location_id',
  // 'fulfillments.packed_at',
  // 'fulfillments.shipped_at',
  // 'fulfillments.delivered_at',
  // 'fulfillments.canceled_at',
  // 'fulfillments.items.id',
  // 'fulfillments.items.quantity',
  // 'fulfillments.labels.id',
  // 'fulfillments.labels.tracking_number',
  'customer.id',
  'customer.email',
  'customer.first_name',
  'customer.last_name',
  'order_set.id',
  'order_set.display_id',
  // Payment information
  'payment_collections.id',
  'payment_collections.status',
  'payment_collections.currency_code',
  'payment_collections.amount',
  'payment_collections.authorized_amount',
  'payment_collections.captured_amount',
  'payment_collections.refunded_amount',
  'payment_collections.created_at',
  'payment_collections.payments.id',
  'payment_collections.payments.provider_id',
  'payment_collections.payments.amount',
  'payment_collections.payments.created_at',
  'payment_collections.payment_sessions.id',
  'payment_collections.payment_sessions.provider_id',
  'payment_collections.payment_sessions.status',
  'payment_collections.payment_sessions.created_at',
]

export const sellerOrderQueryConfig = {
  list: {
    defaults: sellerOrderDefaultFields,
    isList: true
  },
  retrieve: {
    defaults: sellerOrderDefaultFields,
    isList: false
  }
}

export const sellerOrderChangesFields = [
  'id',
  'order_id',
  'return_id',
  'claim_id',
  'exchange_id',
  'version',
  'change_type',
  '*actions',
  'description',
  'status',
  'internal_note',
  'created_by',
  'requested_by',
  'requested_at',
  'confirmed_by',
  'confirmed_at',
  'declined_by',
  'declined_reason',
  'metadata',
  'declined_at',
  'canceled_by',
  'canceled_at',
  'created_at',
  'updated_at'
]

export const sellerOrderChangesDefaultFields = [
  'id',
  'display_id',
  'status',
  'email',
  'currency_code',
  'version',
  'summary',
  'metadata',
  'created_at',
  'updated_at',
  'region_id',
  'total',
  'subtotal',
  'tax_total',
  'order_change',
  'discount_total',
  'discount_tax_total',
  'original_total',
  'original_tax_total',
  'item_total',
  'item_subtotal',
  'item_tax_total',
  'original_item_total',
  'original_item_subtotal',
  'original_item_tax_total',
  'shipping_total',
  'shipping_subtotal',
  'shipping_tax_total',
  'original_shipping_tax_total',
  'original_shipping_subtotal',
  'original_shipping_total',
  'order_set.order_delivery_detail',
  'items.*',
  'items.tax_lines.*',
  'items.adjustments.*',
  'items.variant.*',
  'items.variant.product.*',
  'items.detail.*',
  'shipping_address.*',
  'billing_address.*',
  'shipping_methods.*',
  'shipping_methods.tax_lines.*',
  'shipping_methods.adjustments.*',
  'fulfillments.*',
  'fulfillments.items.*',
  'fulfillments.labels.*',
  'customer.*',
  // 'customer.addresses.*',
  // 'split_order_payment.*',
  // 'order_set.order_delivery_detail.*',
]

export const sellerOrderChangesQueryConfig = {
  list: {
    defaults: sellerOrderChangesDefaultFields,
    isList: true
  },
  retrieve: {
    defaults: sellerOrderChangesDefaultFields,
    isList: false
  }
}
